
server:
    port: 8084

kafka:
  broker:
    hosts: 49.233.91.71:9092
  producer:
    retries: 3
    batch-size: 16384
    linger-ms: 1
    buffer-memory: 33554432
    acks: 1
  default:
    partitions-num: 2
    replication-factor: 3
  consumer:
    group-id: paxvas_app_scan
    auto-commit: false
    auto-commit-interval-ms: 100
    session-timeout-ms: 30000
    container-poll-timeout-ms: 3000
    max-poll-records: 100
    max-poll-interval-ms: 300000
#  listener:
#  #    #listner负责ack，每调用一次，立即commit
#    ack-mode: manual_immediate
  customization:
    listener-ack:
      app: MANUAL_IMMEDIATE