server:
  port: 8084

application:
  version: "@project.version@"

swagger.enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 问题一、必须加上serverTimezone=UTC，不然因为据库和系统时区差错而报错
    url: "jdbc:mysql://localhost:3306/arch?serverTimezone=UTC&allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false"
    username: root
    password: root
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    #问题一、不能直接输入db.migration，而正确的输入应该是db/migration。
    #问题二、文件必须是UTF-8编码，不然会报校验和错误
    locations: classpath:db/migration/common,classpath:db/migration/mysql,classpath:db/migration/java

kafka:
  broker:
    hosts: localhost:9092
  producer:
    retries: 3
    batch-size: 16384
    linger-ms: 1
    buffer-memory: 33554432
    acks: 1
  default:
    partitions-num: 2
    replication-factor: 3
  consumer:
    group-id: paxvas_app_scan
    auto-commit: false
    auto-commit-interval-ms: 100
    session-timeout-ms: 30000
    container-poll-timeout-ms: 3000
    max-poll-records: 100
    max-poll-interval-ms: 300000
#  listener:
#  #    #listner负责ack，每调用一次，立即commit
#    ack-mode: manual_immediate
  customization:
    listener-ack:
      app: MANUAL_IMMEDIATE

mybatis:
  mapper-locations: classpath:mappings/*Mapper.xml

vas-common:
  current-service-type: VAS_PLATFORM
  service-info:
    VAS_PLATFORM:
      deploy-intranet: true
      internet-url: http://www.paxdev.com:8080/platform
      intranet-url: http://platform/platform
      secret-key: S5YwsuB09fEDYKe35U6aqaE01X0UjJYj5QRcGiaYwKhsK01y
  paxstore:
    auth-url: http://%s:8082/passport
    vas-api-url: http://%s:8084/p-market-vas
    bypass-ssl-check: false
    auth-code-process-url: http://www.paxdev.com:8080/platform/auth/code


logging:
  # 用的SpringBoot自带的日志系统 https://www.cnblogs.com/sueyyyy/p/13721976.html
  config: classpath:logback-spring.xml
